# Generated by Django 5.2.6 on 2026-02-03 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Історія карми',
                'verbose_name_plural': 'Історія карми',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='karma_karma_user_id_de5321_idx')],
            },
        ),
    ]
