# Generated by Django 5.2.6 on 2026-07-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_status_d7deb7_idx',
            old_name='reports_status_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_content_0cd725_idx',
            old_name='reports_content_idx',
        ),
    ]
