# Generated by Django 5.2.6 on 2026-02-24 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemovie',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='movierating',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['-added_at']},
        ),
        migrations.RenameField(
            model_name='favoritemovie',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='movierating',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='watchlistitem',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterUniqueTogether(
            name='favoritemovie',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritemovie',
            name='media_type',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='movierating',
            name='media_type',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='movierating',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='media_type',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='favoritemovie',
            unique_together={('user', 'tmdb_id', 'media_type')},
        ),
        migrations.AlterUniqueTogether(
            name='movierating',
            unique_together={('user', 'tmdb_id', 'media_type')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'tmdb_id', 'media_type')},
        ),
    ]
